spring.application.name=backend-impressoes

# ===============================
# CONFIGURAÇÃO DO POSTGRESQL
# ===============================
# spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_impressoes
# spring.datasource.username=postgres
# spring.datasource.password=527463
# spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.lldwbrzkuqumtwkvdlxb
spring.datasource.password=SNOmi4iV4MJaAiwZ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000

# ===============================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# ===============================
# Mostra no terminal os comandos SQL que o Java está fazendo
spring.jpa.show-sql=true

# Formata o SQL no terminal para ficar legível
spring.jpa.properties.hibernate.format_sql=true

# Atualiza as tabelas automaticamente baseado no seu código Java
spring.jpa.hibernate.ddl-auto=update

# Configurações de E-mail (Gmail Real do Kayque)
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PASS}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Para evitar erro de CORS com o React (Vite)
spring.mvc.cors.allowed-origins=http://localhost:5173

