@startuml diagram
' Configurações visuais para deixar o diagrama mais limpo e profissional
hide circle
skinparam linetype ortho
skinparam shadowing false
skinparam class {
    BackgroundColor White
    ArrowColor #26d451
    BorderColor #0b3203
}

' --- Definição dos ENUMS ---
enum CategoriaServico {
  IMPRESSAO
  ENCADERNACAO
}

enum StatusFila {
  PENDENTE
  PRONTO
  CONCLUIDO
  CANCELADO
}

enum Orientacao {
  RETRATO
  PAISAGEM
}

enum TipoCor {
  PRETO_BRANCO
  COLORIDO
}

enum MetodoPagamento {
  PIX
  DINHEIRO
  CARTAO
}

' --- Definição das Classes (Tabelas + Métodos) ---

class "Usuario" as usuario {
  - id_usuario : int
  - nome_completo : String
  - email : String
  - senha : String
  ==
  + autenticarUsuario() // concluido
  + visualizarPerfil() // concluido
  + atualizarPerfil() // concluido
  + recuperarSenha() // concluido
  + alterarSenha() // concluido
  + cadastrarUsuario() // concluido
}

class "Estudante" as estudante {
  --
  - matricula : String
  - curso : String
  ==
}

class "Administrador" as admin {
  --
  ==
  ' Gestão de Pessoas e Acessos
  + cadastrarAdministradorInterno() // concluido
  + gerenciarUsuarios() // concluido
  
  ' Gestão Operacional da Fila (Métodos do PedidoService)
  + listarFilaGlobalAdmin() 
  + chamarProximoPedido() 
  + concluirImpressao(idPedido: int) 
  + obterDetalhesPedido(idPedido: int) 
  + obterNivelOcupacao() 
  + obterStatusFilaGeral()
  
  ' Gestão de Configurações e Preços
  + verificarStatusSetor() // concluido
  + alterarStatusSetor(status: boolean, mensagem: String) // concluido
  + gerenciarPreços(idServico: int, novoPreco: double) // concluido
  + alterarDisponibilidadeServico(idServico: int, disponivel: boolean) // concluido
  
  ' Gestão de Horários // concluido
  + gerenciarHorarios() 
  + cadastrarHorario(dados)
  + atualizarHorario(id, dados)
  + obterQuadroHorariosCompleto()
  
  ' Comunicação e Inteligência
  + visualizarRelatorios() 
  + cadastarNotificacao(titulo, mensagem, idUsuario) 
  + gerenciarSolicitacoes() 
}

class "Servico" as servico {
  - id_servico : int <<PK>>
  --
  - categoria_servico : CategoriaServico
  - preco_unitario : double
  - disponivel : boolean
  ==
  + listarServicos() : List<Servico>
}

class "Pedido" as pedido {
  - id_pedido : int <<PK>>
  --
  - id_usuario : int <<FK>>
  - data_hora : Datetime
  - status_fila : StatusFila
  - arquivo_url : String
  - nome_arquivo_original : String
  - tamanho_arquivo_mb : double
  - total_paginas_arquivo : int
  - valor_total : double
  ==
  + confirmarPedido() // concluido
  + cancelarPedido() // concluido

  + cancelarPedidoAdmin() 

  + atualizarStatusPedido() // concluido

  + obterPosicaoFila() // concluido
  + estimarTempoFila() // concluido
  + listarFilaDePedidos() // concluido

  + obterEstatisticasUsuario() // concluido 
  + listarPedidosAtivos() // concluido
  + listarPedidosHistorico() // concluido
  + listarPedidosPorStatus(status) // concluido
}

class "Item_Pedido" as item_pedido {
  - id_item : int <<PK>>
  --
  - id_pedido : int <<FK>>
  - id_servico : int <<FK>>
  - quantidade : int
  - tamanho_papel : String
  - orientacao : Orientacao
  - frente_verso : boolean
  - tipo_cor : TipoCor
  ==
}

class "Pagamento" as pagamento {
  - id_pagamento : int <<PK>>
  --
  - id_pedido : int <<FK>>
  - metodo : MetodoPagamento
  ==
  + registrarPagamento(idPedido, metodo) // concluido
}

class "Notificacao" as notificacao {
  - id_notificacao : int <<PK>>
  --
  - id_usuario : int <<FK>>
  - titulo : String
  - mensagem : String
  - lida : boolean
  - data_hora : Datetime
  ==
  + listarNotificacoes(idUsuario) 
  + marcarComoLida() 
}

class "Horario_Funcionamento" as horario {
  - id_horario : int <<PK>>
  --
  - dia_semana : String
  - manha : String
  - tarde : String
  - noite : String
  ==

}

class "Configuracao_Sistema" as config {
  - id_config : int <<PK>>
  --
  - setor_aberto : boolean
  - mensagem_aviso : String
  ==
  + enviarNotificacao(idUsuario, mensagem) : void
  + obterQuadroHorariosCompleto() // concluido
}

' --- Definição dos Relacionamentos ---

usuario <|-- estudante
usuario <|-- admin


usuario ||--o{ notificacao : "recebe"
pedido ||--|{ item_pedido : "contém"
servico ||--o{ item_pedido : "é adicionado em"
pedido ||--o| pagamento : "possui"
config ||--o{ horario : "possui"

estudante "1   " -- "0..*  " pedido : "realiza"
admin "1   " -- "0..*  " config : "gerencia"
admin "1   " -- "0..*  " pedido : "gerencia"

@enduml